apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eks-iam-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eks-iam-test
    spec:
      serviceAccountName: iam-test
      containers:
      - name: eks-iam-test
        image: sdscello/awscli:latest
        ports:
        - containerPort: 80
